version: '3'
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    network_mode: 'host'
    volumes:
      - /volume1/docker/cloudflare-ddns/config.json:/config.json