version: '3'
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
    networks:
      - traefik
    volumes:
      - /volume1/docker/homeassistant:/config:rw
    labels:
      my.zone: homeserver
      traefik.enable: true
      traefik.http.routers.homeassistant.rule: Host(`homeassistant.${SERVER_DOMAIN}`)
      traefik.http.routers.homeassistant.entrypoints: websecure
      traefik.http.services.homeassistant.loadbalancer.server.port: 8123
    
networks:
  traefik:
    name: homeserver
    external: true  