version: '3'
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
    volumes:
      - /volume1/docker/homeassistant:/config:rw
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
    