version: '3'
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles      
    networks:
      - traefik
    volumes:
      - /volume1/docker/plex:/config:rw
      - /volume1/Data:/Data:rw
    labels:
      my.zone: homeserver
      traefik.enable: true
      traefik.http.routers.plex.rule: Host(`plex.${SERVER_DOMAIN}`)
      traefik.http.routers.plex.entrypoints: websecure
      traefik.http.services.plex.loadbalancer.server.port: 80

networks:
  traefik:
    name: homeserver
    external: true