version: '3'
services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    network_mode: host
    volumes:
      - /volume1/docker/homebridge:/homebridge:rw
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"