version: '3'
services:
  homebridge:
    image: homebridge/homebridge:ubuntu
    container_name: homebridge
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    network_mode: host
    volumes:
      - /volume1/docker/homebridge:/homebridge:rw