version: '3'
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
    network_mode: host
    volumes:
      - /volume1/docker/pihole/config:/etc/pihole:rw
      - /volume1/docker/pihole/dns:/etc/dnsmasq.d:rw