version: '3'
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
      - ServerIP=192.168.1.177
      - WEBPASSWORD='pihole311'
    cap_add:
      - NET_ADMIN
    networks:
      - traefik
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    volumes:
      - /volume1/docker/pihole/config:/etc/pihole:rw
      - /volume1/docker/pihole/dns:/etc/dnsmasq.d:rw

networks:
  traefik:
    name: pi_network
    external: true